### ISSUE TITLE
Crashing on simple object iteration

### ISSUE THREAD

**Issue by johmarjac** [hinnie123/Mordhau_SDK#1]
Hi,

I dont know why but I get crashes and I think they are not supposed to happen.
This is, how I initialize the SDK
![image](https://i.imgur.com/OIXRiQe.png)

It is printing out thousands of objects correctly and then at some random object it crashes with an AccessViolationException. Why is that happening?

![image](https://i.imgur.com/qCemAMV.png)

Can you try doing the same iteration and tell me if it crashes for you too?
I have already a working cheat but it constantly crashes at some random point with my own player pawn sometimes has a invalid pointer (it is not a NULL Pointer) it is having some weird address which will result in a ACcessViolationException when trying to read. Sometimes I can play 15 minutes, sometimes it crash already after 5 minutes... Its totally random.

That is why I am now working on a completely clean test-project to find issues with the SDK or the game.

Edit: BTW, I am on the MainMenu when calling that. Maybe if you are testing, see if you are also on MainMenu to reproduce

**Comment by hinnie123** [comment]
The sdk has been updated.
